### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by cellerich** [lublak/n8n-nodes-jsonata#1]
if you need help documenting the jsonata node, I could help you out.

**Comment by lublak** [comment]
@cellerich I gladly accept pull requests :)
I would just like to create the base today.
And testing helps me even more!

**Comment by cellerich** [comment]
@lublak glad to help testing, is there a version I can download and install already?

**Comment by lublak** [comment]
@cellerich You can test the dev version like this:
https://docs.n8n.io/integrations/creating-nodes/test/run-node-locally/

But i tested it and it works for me :)
I created a small install description.
I create i release today to you can also install it like any other node.

**Comment by lublak** [comment]
@cellerich should be now avaible
