### ISSUE TITLE
works beautiful - thanks a lot

### ISSUE THREAD

**Issue by cellerich** [lublak/n8n-nodes-jsonata#2]
Just installed Version 1.0.0 and tried it out.
Work as expected and beautifully.

My workflow to use this node is at the moment like this:

- get the JSON from the previous node in n8n
- goto [JSONata Playground](https://try.jsonata.org/)
- paste the JSON into the left side
- write and test my JSONata "statement"
- once working, copy the JSONata statement
- paste it into the n8n-jsonata node as the `query`

Absolutely easiest way to refactor/filter/rearrange some JSON data!

Thanks a lot for this node!

**Comment by lublak** [comment]
@cellerich somehow i overlooked the comment.
Thanks for the kind words, even though I no longer use n8n myself, I'm glad that the node helps other people.
